### PR TITLE
MISC: script verificacion authUser

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento

https://proyectos.andes.gob.ar/browse/MISC-117
### Funcionalidad desarrollada 

1. Script para incluir campos faltantes a registro de authUsers
2. 
3. 

### UserStories llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/MISC-117
- [ ] No

### Requiere actualizaciones en la base de datos

- [x] Si
- [ ] No

`node script authUsers_include_fields`

### CODE REVIEW

**Review by sychus — CHANGES_REQUESTED** [review]
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:6:3 - trailing whitespace
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:9:3 - trailing whitespace
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:14:3 - trailing whitespace
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:18:21 - trailing whitespace
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:19:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:20:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:21:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:22:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:23:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:24:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:25:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:26:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:27:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:28:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:29:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:30:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:31:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:32:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:33:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:34:9 - " should be '
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:51:15 - missing whitespace
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:59:1 - trailing whitespace
ERROR: /home/circleci/project/scripts/authUsers_include_fields.ts:64:14 - file should end with a newline

**Review by sychus — APPROVED** [review]
Lo probe y funciona bien. Para la prueba hice una copia de la colección de producción y actualizó los campos sin fallos. Para completar la tarea faltaría tener estos campos en el esquema y en la interfaz.

**Comment by sychus** [comment]
@condorpiedra @liquid36 Les parece avanzar con esta normalización de campos (aunque algunos vayan en null) o descartamos el PR?

**Comment by liquid36** [comment]
No le encuentro sentido a completar campos en null, pensé que iban a completar los campos active, authMethod con los valores por default. 
El campo active no se usa en ningún lado porque se traslado al array de organizaciónes. Ese tipo de emparejamiento pensaba.

**Comment by sychus** [comment]
Lo cerramos. Vamos a re pensar como realizar el empajeramiento mejor.

**Pull request closed without merging**
