### PR TITLE
feat(JOB): Exportación a sisa de casos covid

### PR DESCRIPTION
**Pull request by silviroa**
### Requerimiento
Exportar casos covid registrados en Andes como confirmados por nexos o confirmados por test rapido de antigenos

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Review by sychus — APPROVED** [review]

**Review by condorpiedra — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3070](http://condorpiedra.andes.gob.ar:85/3070/mochawesome.html)
CYPRESS RUN: [2197](https://dashboard.cypress.io/projects/xr7gft/runs/2197/specs)
TEST START: 2021-01-13T14:26:33.441Z
TOTAL: 351
SUCCESS: 342
FAIL: 9
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3071](http://condorpiedra.andes.gob.ar:85/3071/mochawesome.html)
CYPRESS RUN: [2198](https://dashboard.cypress.io/projects/xr7gft/runs/2198/specs)
TEST START: 2021-01-13T14:41:34.673Z
TOTAL: 351
SUCCESS: 342
FAIL: 9
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3073](http://condorpiedra.andes.gob.ar:85/3073/mochawesome.html)
CYPRESS RUN: [2200](https://dashboard.cypress.io/projects/xr7gft/runs/2200/specs)
TEST START: 2021-01-13T15:39:31.386Z
TOTAL: 351
SUCCESS: 347
FAIL: 4
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3075](http://condorpiedra.andes.gob.ar:85/3075/mochawesome.html)
CYPRESS RUN: [2202](https://dashboard.cypress.io/projects/xr7gft/runs/2202/specs)
TEST START: 2021-01-13T16:15:38.649Z
TOTAL: 351
SUCCESS: 349
FAIL: 2
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3079](http://condorpiedra.andes.gob.ar:85/3079/mochawesome.html)
CYPRESS RUN: [2206](https://dashboard.cypress.io/projects/xr7gft/runs/2206/specs)
TEST START: 2021-01-13T17:06:02.388Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

**Pull request merged**
