### PR TITLE
RUP - Nueva molecula ACV

### PR DESCRIPTION
**Pull request by negro89**
### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-329

### Funcionalidad desarrollada 

1. Agrega atributo 'params' a esquema de registros de prestacion.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [X] Si (Ver pr app https://github.com/andes/app/pull/2752)
- [ ] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7616](http://condorpiedra.andes.gob.ar:85/7616/mochawesome.html)
CYPRESS RUN: [6461](https://dashboard.cypress.io/projects/xr7gft/runs/6461/specs)
TEST START: 2022-09-13T19:25:52.314Z
TOTAL: 374
SUCCESS: 362
FAIL: 11
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7624](http://condorpiedra.andes.gob.ar:85/7624/mochawesome.html)
CYPRESS RUN: [6469](https://dashboard.cypress.io/projects/xr7gft/runs/6469/specs)
TEST START: 2022-09-14T13:36:21.772Z
TOTAL: 406
SUCCESS: 401
FAIL: 4
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7632](http://condorpiedra.andes.gob.ar:85/7632/mochawesome.html)
CYPRESS RUN: [6478](https://dashboard.cypress.io/projects/xr7gft/runs/6478/specs)
TEST START: 2022-09-14T16:58:59.398Z
TOTAL: 406
SUCCESS: 401
FAIL: 4
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7735](http://condorpiedra.andes.gob.ar:85/7735/mochawesome.html)
CYPRESS RUN: [6853](https://dashboard.cypress.io/projects/xr7gft/runs/6853/specs)
TEST START: 2022-10-06T15:43:28.536Z
TOTAL: 342
SUCCESS: 326
FAIL: 15
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7752](http://condorpiedra.andes.gob.ar:85/7752/mochawesome.html)
CYPRESS RUN: [6890](https://dashboard.cypress.io/projects/xr7gft/runs/6890/specs)
TEST START: 2022-10-14T15:43:10.682Z
TOTAL: 359
SUCCESS: 345
FAIL: 13
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7757](http://condorpiedra.andes.gob.ar:85/7757/mochawesome.html)
CYPRESS RUN: [6895](https://dashboard.cypress.io/projects/xr7gft/runs/6895/specs)
TEST START: 2022-10-14T18:23:16.391Z
TOTAL: 363
SUCCESS: 343
FAIL: 19
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: silviroa  
BUILD NUMBER: [8260](http://condorpiedra.andes.gob.ar:85/8260/mochawesome.html)
CYPRESS RUN: [7441](https://dashboard.cypress.io/projects/xr7gft/runs/7441/specs)
TEST START: 2023-01-17T18:10:50.848Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

**Review by silviroa — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8274](http://condorpiedra.andes.gob.ar:85/8274/mochawesome.html)
CYPRESS RUN: [7455](https://dashboard.cypress.io/projects/xr7gft/runs/7455/specs)
TEST START: 2023-01-18T18:20:36.831Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8278](http://condorpiedra.andes.gob.ar:85/8278/mochawesome.html)
CYPRESS RUN: [7459](https://dashboard.cypress.io/projects/xr7gft/runs/7459/specs)
TEST START: 2023-01-18T19:09:52.860Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [8336](http://condorpiedra.andes.gob.ar:85/8336/mochawesome.html)
CYPRESS RUN: [7515](https://dashboard.cypress.io/projects/xr7gft/runs/7515/specs)
TEST START: 2023-01-26T16:01:51.071Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

**Review by MCele — APPROVED** [review]

**Pull request merged**
