### PR TITLE
GDU - Agregar filtro en listado de perfiles

### PR DESCRIPTION
**Pull request by maring0019**
### Requerimiento

https://proyectos.andes.gob.ar/browse/GDU-51
https://proyectos.andes.gob.ar/browse/GDU-52
### Funcionalidad desarrollada 

1. Se agrega un filtro que permite buscar por nombre del perfil. 
2. Se agrega un filtro por el campo activo. 

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [7705](http://condorpiedra.andes.gob.ar:85/7705/mochawesome.html)
CYPRESS RUN: [6696](https://dashboard.cypress.io/projects/xr7gft/runs/6696/specs)
TEST START: 2022-09-29T14:02:58.959Z
TOTAL: 401
SUCCESS: 398
FAIL: 2
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [7710](http://condorpiedra.andes.gob.ar:85/7710/mochawesome.html)
CYPRESS RUN: [6701](https://dashboard.cypress.io/projects/xr7gft/runs/6701/specs)
TEST START: 2022-09-29T17:42:29.350Z
TOTAL: 401
SUCCESS: 391
FAIL: 9
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [7718](http://condorpiedra.andes.gob.ar:85/7718/mochawesome.html)
CYPRESS RUN: [6713](https://dashboard.cypress.io/projects/xr7gft/runs/6713/specs)
TEST START: 2022-09-30T14:56:27.273Z
TOTAL: 401
SUCCESS: 397
FAIL: 3
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [7719](http://condorpiedra.andes.gob.ar:85/7719/mochawesome.html)
CYPRESS RUN: [6719](https://dashboard.cypress.io/projects/xr7gft/runs/6719/specs)
TEST START: 2022-09-30T15:10:31.727Z
TOTAL: 401
SUCCESS: 398
FAIL: 2
SKIPPED: 1

**Comment by maring0019** [comment]
Falta realizar test.

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [7920](http://condorpiedra.andes.gob.ar:85/7920/mochawesome.html)
CYPRESS RUN: [7115](https://dashboard.cypress.io/projects/xr7gft/runs/7115/specs)
TEST START: 2022-11-14T16:34:05.833Z
TOTAL: 401
SUCCESS: 388
FAIL: 12
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [7927](http://condorpiedra.andes.gob.ar:85/7927/mochawesome.html)
CYPRESS RUN: [7122](https://dashboard.cypress.io/projects/xr7gft/runs/7122/specs)
TEST START: 2022-11-15T15:54:18.283Z
TOTAL: 401
SUCCESS: 396
FAIL: 4
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8024](http://condorpiedra.andes.gob.ar:85/8024/mochawesome.html)
CYPRESS RUN: [7217](https://dashboard.cypress.io/projects/xr7gft/runs/7217/specs)
TEST START: 2022-11-28T16:44:34.167Z
TOTAL: 387
SUCCESS: 378
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8028](http://condorpiedra.andes.gob.ar:85/8028/mochawesome.html)
CYPRESS RUN: [7221](https://dashboard.cypress.io/projects/xr7gft/runs/7221/specs)
TEST START: 2022-11-28T21:13:45.664Z
TOTAL: 401
SUCCESS: 382
FAIL: 17
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8038](http://condorpiedra.andes.gob.ar:85/8038/mochawesome.html)
CYPRESS RUN: [7231](https://dashboard.cypress.io/projects/xr7gft/runs/7231/specs)
TEST START: 2022-11-29T17:21:05.014Z
TOTAL: 401
SUCCESS: 389
FAIL: 10
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8045](http://condorpiedra.andes.gob.ar:85/8045/mochawesome.html)
CYPRESS RUN: [7238](https://dashboard.cypress.io/projects/xr7gft/runs/7238/specs)
TEST START: 2022-11-30T12:52:32.287Z
TOTAL: 350
SUCCESS: 339
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8088](http://condorpiedra.andes.gob.ar:85/8088/mochawesome.html)
CYPRESS RUN: [7280](https://dashboard.cypress.io/projects/xr7gft/runs/7280/specs)
TEST START: 2022-12-05T17:09:58.736Z
TOTAL: 401
SUCCESS: 389
FAIL: 10
SKIPPED: 2

**Pull request closed without merging**
