### PR TITLE
EP: ignorar seguimiento en apertura ficha

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento

https://proyectos.andes.gob.ar/browse/EP-176
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5786](http://condorpiedra.andes.gob.ar:85/5786/mochawesome.html)
CYPRESS RUN: [4709](https://dashboard.cypress.io/projects/xr7gft/runs/4709/specs)
TEST START: 2022-01-07T14:19:15.526Z
TOTAL: 379
SUCCESS: 371
FAIL: 7
SKIPPED: 1

**Review by martinebucarey — APPROVED** [review]

**Review by liquid36 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5801](http://condorpiedra.andes.gob.ar:85/5801/mochawesome.html)
CYPRESS RUN: [4724](https://dashboard.cypress.io/projects/xr7gft/runs/4724/specs)
TEST START: 2022-01-11T14:30:47.608Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5802](http://condorpiedra.andes.gob.ar:85/5802/mochawesome.html)
CYPRESS RUN: [4725](https://dashboard.cypress.io/projects/xr7gft/runs/4725/specs)
TEST START: 2022-01-11T14:44:23.029Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5806](http://condorpiedra.andes.gob.ar:85/5806/mochawesome.html)
CYPRESS RUN: [4729](https://dashboard.cypress.io/projects/xr7gft/runs/4729/specs)
TEST START: 2022-01-11T16:10:48.187Z
TOTAL: 404
SUCCESS: 396
FAIL: 7
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5807](http://condorpiedra.andes.gob.ar:85/5807/mochawesome.html)
CYPRESS RUN: [4730](https://dashboard.cypress.io/projects/xr7gft/runs/4730/specs)
TEST START: 2022-01-11T16:20:04.343Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5808](http://condorpiedra.andes.gob.ar:85/5808/mochawesome.html)
CYPRESS RUN: [4731](https://dashboard.cypress.io/projects/xr7gft/runs/4731/specs)
TEST START: 2022-01-11T16:34:23.743Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

**Pull request merged**
