### PR TITLE
MPI - Elimina ruta en desuso

### PR DESCRIPTION
**Pull request by negro89**
### Requerimiento
Eliminar endpoint (Get historial de turnos) en api de paciente

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Review by juuliotero — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [3290](http://condorpiedra.andes.gob.ar:85/3290/mochawesome.html)
CYPRESS RUN: [2405](https://dashboard.cypress.io/projects/xr7gft/runs/2405/specs)
TEST START: 2021-02-11T11:46:16.492Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

**Review by palita1991 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [3292](http://condorpiedra.andes.gob.ar:85/3292/mochawesome.html)
CYPRESS RUN: [2407](https://dashboard.cypress.io/projects/xr7gft/runs/2407/specs)
TEST START: 2021-02-11T12:54:26.586Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [3300](http://condorpiedra.andes.gob.ar:85/3300/mochawesome.html)
CYPRESS RUN: [2415](https://dashboard.cypress.io/projects/xr7gft/runs/2415/specs)
TEST START: 2021-02-11T15:25:50.935Z
TOTAL: 324
SUCCESS: 310
FAIL: 13
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [3320](http://condorpiedra.andes.gob.ar:85/3320/mochawesome.html)
CYPRESS RUN: [2431](https://dashboard.cypress.io/projects/xr7gft/runs/2431/specs)
TEST START: 2021-02-12T15:39:46.895Z
TOTAL: 358
SUCCESS: 349
FAIL: 8
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [3321](http://condorpiedra.andes.gob.ar:85/3321/mochawesome.html)
CYPRESS RUN: [2432](https://dashboard.cypress.io/projects/xr7gft/runs/2432/specs)
TEST START: 2021-02-12T16:04:37.038Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

**Comment by palita1991** [comment]
> USUARIO: lmlagos
> BUILD NUMBER: [3321](http://condorpiedra.andes.gob.ar:85/3321/mochawesome.html)
> CYPRESS RUN: [2432](https://dashboard.cypress.io/projects/xr7gft/runs/2432/specs)
> TEST START: 2021-02-12T16:04:37.038Z
> TOTAL: 358
> SUCCESS: 357
> FAIL: 0
> SKIPPED: 1

Vamooo @negro89 querido

**Review by MCele — APPROVED** [review]

**Comment by condorpiedra** [comment]
Se cierra PR hasta realizar el refactor del historial de turnos por paciente

**Pull request closed without merging**
