### PR TITLE
CIT - Repara error al reasignar turnos asociados a solicitudes TOP

### PR DESCRIPTION
**Pull request by ma7payne**
### Funcionalidad desarrollada 

1. Modifica condicion en tipo de turno, para ser contemplado al momento de suspender la agenda.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10408](http://condorpiedra.andes.gob.ar:85/10408/mochawesome.html)
CYPRESS RUN: [9513](https://dashboard.cypress.io/projects/xr7gft/runs/9513/specs)
TEST START: 2024-01-31T16:07:53.330Z
TOTAL: 357
SUCCESS: 344
FAIL: 10
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10410](http://condorpiedra.andes.gob.ar:85/10410/mochawesome.html)
CYPRESS RUN: [9515](https://dashboard.cypress.io/projects/xr7gft/runs/9515/specs)
TEST START: 2024-01-31T17:54:15.507Z
TOTAL: 306
SUCCESS: 287
FAIL: 16
SKIPPED: 3
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10412](http://condorpiedra.andes.gob.ar:85/10412/mochawesome.html)
CYPRESS RUN: [9517](https://dashboard.cypress.io/projects/xr7gft/runs/9517/specs)
TEST START: 2024-01-31T18:56:21.823Z
TOTAL: 365
SUCCESS: 356
FAIL: 6
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10417](http://condorpiedra.andes.gob.ar:85/10417/mochawesome.html)
CYPRESS RUN: [9522](https://dashboard.cypress.io/projects/xr7gft/runs/9522/specs)
TEST START: 2024-02-01T13:59:10.175Z
TOTAL: 402
SUCCESS: 398
FAIL: 1
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10419](http://condorpiedra.andes.gob.ar:85/10419/mochawesome.html)
CYPRESS RUN: [9524](https://dashboard.cypress.io/projects/xr7gft/runs/9524/specs)
TEST START: 2024-02-01T14:31:03.415Z
TOTAL: 276
SUCCESS: 248
FAIL: 25
SKIPPED: 3
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10420](http://condorpiedra.andes.gob.ar:85/10420/mochawesome.html)
CYPRESS RUN: [9525](https://dashboard.cypress.io/projects/xr7gft/runs/9525/specs)
TEST START: 2024-02-01T14:42:26.870Z
TOTAL: 402
SUCCESS: 399
FAIL: 0
SKIPPED: 3

**Review by negro89 — APPROVED** [review]

**Pull request merged**
