### PR TITLE
VAC - Dación de turno desde la inscripción

### PR DESCRIPTION
**Pull request by negro89**
### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-83

### Funcionalidad desarrollada 

1. Agrega datos del turno al esquema de inscripción a vacunación

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [4448](http://condorpiedra.andes.gob.ar:85/4448/mochawesome.html)
CYPRESS RUN: [3465](https://dashboard.cypress.io/projects/xr7gft/runs/3465/specs)
TEST START: 2021-06-29T14:13:12.522Z
TOTAL: 398
SUCCESS: 397
FAIL: 0
SKIPPED: 1

**Review by plammel — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [4753](http://condorpiedra.andes.gob.ar:85/4753/mochawesome.html)
CYPRESS RUN: [3749](https://dashboard.cypress.io/projects/xr7gft/runs/3749/specs)
TEST START: 2021-07-29T13:33:55.941Z
TOTAL: 341
SUCCESS: 326
FAIL: 14
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [4754](http://condorpiedra.andes.gob.ar:85/4754/mochawesome.html)
CYPRESS RUN: [3750](https://dashboard.cypress.io/projects/xr7gft/runs/3750/specs)
TEST START: 2021-07-29T14:52:05.485Z
TOTAL: 382
SUCCESS: 379
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [4755](http://condorpiedra.andes.gob.ar:85/4755/mochawesome.html)
CYPRESS RUN: [3751](https://dashboard.cypress.io/projects/xr7gft/runs/3751/specs)
TEST START: 2021-07-29T15:04:57.216Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [4756](http://condorpiedra.andes.gob.ar:85/4756/mochawesome.html)
CYPRESS RUN: [3752](https://dashboard.cypress.io/projects/xr7gft/runs/3752/specs)
TEST START: 2021-07-29T15:40:46.461Z
TOTAL: 334
SUCCESS: 321
FAIL: 12
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [4773](http://condorpiedra.andes.gob.ar:85/4773/mochawesome.html)
CYPRESS RUN: [3769](https://dashboard.cypress.io/projects/xr7gft/runs/3769/specs)
TEST START: 2021-08-03T11:54:06.222Z
TOTAL: 370
SUCCESS: 355
FAIL: 14
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [4776](http://condorpiedra.andes.gob.ar:85/4776/mochawesome.html)
CYPRESS RUN: [3772](https://dashboard.cypress.io/projects/xr7gft/runs/3772/specs)
TEST START: 2021-08-03T12:48:03.398Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [4796](http://condorpiedra.andes.gob.ar:85/4796/mochawesome.html)
CYPRESS RUN: [3791](https://dashboard.cypress.io/projects/xr7gft/runs/3791/specs)
TEST START: 2021-08-04T11:49:52.008Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

**Review by kroce — APPROVED** [review]

**Review by palita1991 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: cceleste  
BUILD NUMBER: [4821](http://condorpiedra.andes.gob.ar:85/4821/mochawesome.html)
CYPRESS RUN: [3815](https://dashboard.cypress.io/projects/xr7gft/runs/3815/specs)
TEST START: 2021-08-06T15:20:26.031Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

**Pull request merged**
