### PR TITLE
MPI: Condición trimestral para devolución de obra social de un paciente

### PR DESCRIPTION
**Pull request by ma7payne**
### Requerimiento

https://proyectos.andes.gob.ar/browse/MPI-402

Asociado a https://glpi.andes.gob.ar/front/ticket.form.php?id=3650
### Funcionalidad desarrollada 

1. Se determina un periodo de tres meses para la recuperación de una obra social de un paciente, basado en la versión del padrón proveniente de PUCO.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

- [X] Si https://github.com/andes/andes-test-integracion/pull/511
- [ ] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [8428](http://condorpiedra.andes.gob.ar:85/8428/mochawesome.html)
CYPRESS RUN: [7603](https://dashboard.cypress.io/projects/xr7gft/runs/7603/specs)
TEST START: 2023-02-17T19:18:02.001Z
TOTAL: 359
SUCCESS: 336
FAIL: 21
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [8622](http://condorpiedra.andes.gob.ar:85/8622/mochawesome.html)
CYPRESS RUN: [7799](https://dashboard.cypress.io/projects/xr7gft/runs/7799/specs)
TEST START: 2023-03-22T20:51:17.614Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [8987](http://condorpiedra.andes.gob.ar:85/8987/mochawesome.html)
CYPRESS RUN: [8150](https://dashboard.cypress.io/projects/xr7gft/runs/8150/specs)
TEST START: 2023-06-02T13:52:32.453Z
TOTAL: 403
SUCCESS: 396
FAIL: 5
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [9438](http://condorpiedra.andes.gob.ar:85/9438/mochawesome.html)
CYPRESS RUN: [8575](https://dashboard.cypress.io/projects/xr7gft/runs/8575/specs)
TEST START: 2023-08-16T14:18:59.354Z
TOTAL: 366
SUCCESS: 354
FAIL: 10
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [9446](http://condorpiedra.andes.gob.ar:85/9446/mochawesome.html)
CYPRESS RUN: [8577](https://dashboard.cypress.io/projects/xr7gft/runs/8577/specs)
TEST START: 2023-08-16T15:58:05.514Z
TOTAL: 403
SUCCESS: 395
FAIL: 6
SKIPPED: 2

**Comment by MCele** [comment]
Revisar test

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [10334](http://condorpiedra.andes.gob.ar:85/10334/mochawesome.html)
CYPRESS RUN: [9441](https://dashboard.cypress.io/projects/xr7gft/runs/9441/specs)
TEST START: 2024-01-25T14:16:26.946Z
TOTAL: 401
SUCCESS: 395
FAIL: 3
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [10336](http://condorpiedra.andes.gob.ar:85/10336/mochawesome.html)
CYPRESS RUN: [9443](https://dashboard.cypress.io/projects/xr7gft/runs/9443/specs)
TEST START: 2024-01-25T14:41:58.614Z
TOTAL: 401
SUCCESS: 393
FAIL: 5
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [10339](http://condorpiedra.andes.gob.ar:85/10339/mochawesome.html)
CYPRESS RUN: [9446](https://dashboard.cypress.io/projects/xr7gft/runs/9446/specs)
TEST START: 2024-01-25T17:56:14.365Z
TOTAL: 355
SUCCESS: 341
FAIL: 11
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10366](http://condorpiedra.andes.gob.ar:85/10366/mochawesome.html)
CYPRESS RUN: [9473](https://dashboard.cypress.io/projects/xr7gft/runs/9473/specs)
TEST START: 2024-01-29T12:25:40.340Z
TOTAL: 401
SUCCESS: 394
FAIL: 4
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10380](http://condorpiedra.andes.gob.ar:85/10380/mochawesome.html)
CYPRESS RUN: [9487](https://dashboard.cypress.io/projects/xr7gft/runs/9487/specs)
TEST START: 2024-01-29T16:23:00.968Z
TOTAL: 355
SUCCESS: 346
FAIL: 6
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10383](http://condorpiedra.andes.gob.ar:85/10383/mochawesome.html)
CYPRESS RUN: [9490](https://dashboard.cypress.io/projects/xr7gft/runs/9490/specs)
TEST START: 2024-01-29T17:33:50.888Z
TOTAL: 280
SUCCESS: 250
FAIL: 28
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10385](http://condorpiedra.andes.gob.ar:85/10385/mochawesome.html)
CYPRESS RUN: [9492](https://dashboard.cypress.io/projects/xr7gft/runs/9492/specs)
TEST START: 2024-01-29T18:46:14.933Z
TOTAL: 401
SUCCESS: 390
FAIL: 8
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10387](http://condorpiedra.andes.gob.ar:85/10387/mochawesome.html)
CYPRESS RUN: [9494](https://dashboard.cypress.io/projects/xr7gft/runs/9494/specs)
TEST START: 2024-01-29T19:16:07.418Z
TOTAL: 369
SUCCESS: 361
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10392](http://condorpiedra.andes.gob.ar:85/10392/mochawesome.html)
CYPRESS RUN: [9499](https://dashboard.cypress.io/projects/xr7gft/runs/9499/specs)
TEST START: 2024-01-30T12:05:46.819Z
TOTAL: 401
SUCCESS: 395
FAIL: 3
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10404](http://condorpiedra.andes.gob.ar:85/10404/mochawesome.html)
CYPRESS RUN: [9510](https://dashboard.cypress.io/projects/xr7gft/runs/9510/specs)
TEST START: 2024-01-30T18:19:29.367Z
TOTAL: 292
SUCCESS: 262
FAIL: 27
SKIPPED: 3
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10406](http://condorpiedra.andes.gob.ar:85/10406/mochawesome.html)
CYPRESS RUN: [9512](https://dashboard.cypress.io/projects/xr7gft/runs/9512/specs)
TEST START: 2024-01-31T15:48:34.882Z
TOTAL: 401
SUCCESS: 396
FAIL: 2
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10409](http://condorpiedra.andes.gob.ar:85/10409/mochawesome.html)
CYPRESS RUN: [9514](https://dashboard.cypress.io/projects/xr7gft/runs/9514/specs)
TEST START: 2024-01-31T17:39:00.810Z
TOTAL: 402
SUCCESS: 396
FAIL: 3
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10411](http://condorpiedra.andes.gob.ar:85/10411/mochawesome.html)
CYPRESS RUN: [9516](https://dashboard.cypress.io/projects/xr7gft/runs/9516/specs)
TEST START: 2024-01-31T18:50:24.309Z
TOTAL: 402
SUCCESS: 392
FAIL: 7
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10416](http://condorpiedra.andes.gob.ar:85/10416/mochawesome.html)
CYPRESS RUN: [9521](https://dashboard.cypress.io/projects/xr7gft/runs/9521/specs)
TEST START: 2024-02-01T13:44:19.061Z
TOTAL: 402
SUCCESS: 399
FAIL: 0
SKIPPED: 3

**Review by MCele — APPROVED** [review]

**Review by negro89 — APPROVED** [review]

**Pull request merged**
