### PR TITLE
TABLAS MAESTRAS - Nuevo filtro tm/profesional

### PR DESCRIPTION
**Pull request by maring0019**
### Requerimiento

https://proyectos.andes.gob.ar/browse/TM-27
### Funcionalidad desarrollada 

1.  Se agrega nueva condición de filtro para profesionales no matriculados.
2. 
3. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Review by MarianoCampetella — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9569](http://condorpiedra.andes.gob.ar:85/9569/mochawesome.html)
CYPRESS RUN: [8692](https://dashboard.cypress.io/projects/xr7gft/runs/8692/specs)
TEST START: 2023-09-06T16:27:49.926Z
TOTAL: 377
SUCCESS: 367
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9573](http://condorpiedra.andes.gob.ar:85/9573/mochawesome.html)
CYPRESS RUN: [8694](https://dashboard.cypress.io/projects/xr7gft/runs/8694/specs)
TEST START: 2023-09-06T18:08:58.324Z
TOTAL: 403
SUCCESS: 397
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9593](http://condorpiedra.andes.gob.ar:85/9593/mochawesome.html)
CYPRESS RUN: [8711](https://dashboard.cypress.io/projects/xr7gft/runs/8711/specs)
TEST START: 2023-09-11T14:16:09.696Z
TOTAL: 353
SUCCESS: 346
FAIL: 5
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9596](http://condorpiedra.andes.gob.ar:85/9596/mochawesome.html)
CYPRESS RUN: [8714](https://dashboard.cypress.io/projects/xr7gft/runs/8714/specs)
TEST START: 2023-09-11T16:49:34.225Z
TOTAL: 370
SUCCESS: 361
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9604](http://condorpiedra.andes.gob.ar:85/9604/mochawesome.html)
CYPRESS RUN: [8720](https://dashboard.cypress.io/projects/xr7gft/runs/8720/specs)
TEST START: 2023-09-12T16:41:46.729Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Review by negro89 — APPROVED** [review]

**Pull request merged**
