### PR TITLE
IN - Agrega audit para updatedAt y createdBy en internaciones

### PR DESCRIPTION
**Pull request by ma7payne**
### Requerimiento

https://proyectos.andes.gob.ar/browse/IN-565

### Funcionalidad desarrollada 

1. Se incorpora plugin Audit para generar las fechas createdAt y updatedBy en internaciones

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [9744](http://condorpiedra.andes.gob.ar:85/9744/mochawesome.html)
CYPRESS RUN: [8855](https://dashboard.cypress.io/projects/xr7gft/runs/8855/specs)
TEST START: 2023-10-05T17:46:45.014Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [9746](http://condorpiedra.andes.gob.ar:85/9746/mochawesome.html)
CYPRESS RUN: [8856](https://dashboard.cypress.io/projects/xr7gft/runs/8856/specs)
TEST START: 2023-10-05T18:09:45.463Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [9749](http://condorpiedra.andes.gob.ar:85/9749/mochawesome.html)
CYPRESS RUN: [8859](https://dashboard.cypress.io/projects/xr7gft/runs/8859/specs)
TEST START: 2023-10-05T19:01:55.276Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [9750](http://condorpiedra.andes.gob.ar:85/9750/mochawesome.html)
CYPRESS RUN: [8860](https://dashboard.cypress.io/projects/xr7gft/runs/8860/specs)
TEST START: 2023-10-05T19:12:21.373Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Review by negro89 — APPROVED** [review]

**Pull request merged**
