### PR TITLE
fix(job): cambia frecuencia

### PR DESCRIPTION
**Pull request by condorpiedra**
### Requerimiento
Cambia la frecuencia para exportar los casos por nexo de Sisa

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3220](http://condorpiedra.andes.gob.ar:85/3220/mochawesome.html)
CYPRESS RUN: [2342](https://dashboard.cypress.io/projects/xr7gft/runs/2342/specs)
TEST START: 2021-02-04T19:08:43.931Z
TOTAL: 336
SUCCESS: 335
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3223](http://condorpiedra.andes.gob.ar:85/3223/mochawesome.html)
CYPRESS RUN: [2345](https://dashboard.cypress.io/projects/xr7gft/runs/2345/specs)
TEST START: 2021-02-05T11:05:46.064Z
TOTAL: 301
SUCCESS: 289
FAIL: 12
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3224](http://condorpiedra.andes.gob.ar:85/3224/mochawesome.html)
CYPRESS RUN: [2346](https://dashboard.cypress.io/projects/xr7gft/runs/2346/specs)
TEST START: 2021-02-05T11:39:48.493Z
TOTAL: 354
SUCCESS: 351
FAIL: 3
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3225](http://condorpiedra.andes.gob.ar:85/3225/mochawesome.html)
CYPRESS RUN: [2347](https://dashboard.cypress.io/projects/xr7gft/runs/2347/specs)
TEST START: 2021-02-05T11:52:57.872Z
TOTAL: 354
SUCCESS: 347
FAIL: 7
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: nhuenchuman  
BUILD NUMBER: [3226](http://condorpiedra.andes.gob.ar:85/3226/mochawesome.html)
CYPRESS RUN: [2348](https://dashboard.cypress.io/projects/xr7gft/runs/2348/specs)
TEST START: 2021-02-05T12:01:24.934Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

**Review by kroce — APPROVED** [review]

**Pull request merged**
