### PR TITLE
TOP: Continuidad a solicitud contrarreferida

### PR DESCRIPTION
**Pull request by Fabio-Ramirez**
### Requerimiento

https://proyectos.andes.gob.ar/browse/TOP-153

### Funcionalidad desarrollada 

1. Se agrega el estado correspondiente en el caso de referir.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Review by MarianoCampetella — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9640](http://condorpiedra.andes.gob.ar:85/9640/mochawesome.html)
CYPRESS RUN: [8754](https://dashboard.cypress.io/projects/xr7gft/runs/8754/specs)
TEST START: 2023-09-19T13:46:13.784Z
TOTAL: 402
SUCCESS: 398
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9641](http://condorpiedra.andes.gob.ar:85/9641/mochawesome.html)
CYPRESS RUN: [8755](https://dashboard.cypress.io/projects/xr7gft/runs/8755/specs)
TEST START: 2023-09-19T14:37:40.301Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9643](http://condorpiedra.andes.gob.ar:85/9643/mochawesome.html)
CYPRESS RUN: [8757](https://dashboard.cypress.io/projects/xr7gft/runs/8757/specs)
TEST START: 2023-09-19T15:33:17.309Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9670](http://condorpiedra.andes.gob.ar:85/9670/mochawesome.html)
CYPRESS RUN: [8784](https://dashboard.cypress.io/projects/xr7gft/runs/8784/specs)
TEST START: 2023-09-27T15:13:23.306Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9671](http://condorpiedra.andes.gob.ar:85/9671/mochawesome.html)
CYPRESS RUN: [8785](https://dashboard.cypress.io/projects/xr7gft/runs/8785/specs)
TEST START: 2023-09-27T15:23:17.737Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9672](http://condorpiedra.andes.gob.ar:85/9672/mochawesome.html)
CYPRESS RUN: [8786](https://dashboard.cypress.io/projects/xr7gft/runs/8786/specs)
TEST START: 2023-09-27T15:42:54.259Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9838](http://condorpiedra.andes.gob.ar:85/9838/mochawesome.html)
CYPRESS RUN: [8946](https://dashboard.cypress.io/projects/xr7gft/runs/8946/specs)
TEST START: 2023-10-30T13:09:52.815Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Review by negro89 — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9860](http://condorpiedra.andes.gob.ar:85/9860/mochawesome.html)
CYPRESS RUN: [8967](https://dashboard.cypress.io/projects/xr7gft/runs/8967/specs)
TEST START: 2023-11-01T16:44:30.963Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9862](http://condorpiedra.andes.gob.ar:85/9862/mochawesome.html)
CYPRESS RUN: [8969](https://dashboard.cypress.io/projects/xr7gft/runs/8969/specs)
TEST START: 2023-11-01T18:06:43.684Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9896](http://condorpiedra.andes.gob.ar:85/9896/mochawesome.html)
CYPRESS RUN: [9003](https://dashboard.cypress.io/projects/xr7gft/runs/9003/specs)
TEST START: 2023-11-10T14:49:22.382Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9898](http://condorpiedra.andes.gob.ar:85/9898/mochawesome.html)
CYPRESS RUN: [9005](https://dashboard.cypress.io/projects/xr7gft/runs/9005/specs)
TEST START: 2023-11-10T15:08:49.054Z
TOTAL: 360
SUCCESS: 351
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9900](http://condorpiedra.andes.gob.ar:85/9900/mochawesome.html)
CYPRESS RUN: [9007](https://dashboard.cypress.io/projects/xr7gft/runs/9007/specs)
TEST START: 2023-11-10T16:05:32.078Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9945](http://condorpiedra.andes.gob.ar:85/9945/mochawesome.html)
CYPRESS RUN: [9052](https://dashboard.cypress.io/projects/xr7gft/runs/9052/specs)
TEST START: 2023-11-22T16:23:53.693Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9951](http://condorpiedra.andes.gob.ar:85/9951/mochawesome.html)
CYPRESS RUN: [9058](https://dashboard.cypress.io/projects/xr7gft/runs/9058/specs)
TEST START: 2023-11-22T19:12:28.252Z
TOTAL: 403
SUCCESS: 391
FAIL: 10
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9953](http://condorpiedra.andes.gob.ar:85/9953/mochawesome.html)
CYPRESS RUN: [9060](https://dashboard.cypress.io/projects/xr7gft/runs/9060/specs)
TEST START: 2023-11-23T12:05:42.351Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9954](http://condorpiedra.andes.gob.ar:85/9954/mochawesome.html)
CYPRESS RUN: [9061](https://dashboard.cypress.io/projects/xr7gft/runs/9061/specs)
TEST START: 2023-11-23T12:22:18.725Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9955](http://condorpiedra.andes.gob.ar:85/9955/mochawesome.html)
CYPRESS RUN: [9062](https://dashboard.cypress.io/projects/xr7gft/runs/9062/specs)
TEST START: 2023-11-23T13:34:29.226Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9967](http://condorpiedra.andes.gob.ar:85/9967/mochawesome.html)
CYPRESS RUN: [9078](https://dashboard.cypress.io/projects/xr7gft/runs/9078/specs)
TEST START: 2023-11-27T11:52:56.310Z
TOTAL: 403
SUCCESS: 397
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9968](http://condorpiedra.andes.gob.ar:85/9968/mochawesome.html)
CYPRESS RUN: [9079](https://dashboard.cypress.io/projects/xr7gft/runs/9079/specs)
TEST START: 2023-11-27T12:08:27.253Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9976](http://condorpiedra.andes.gob.ar:85/9976/mochawesome.html)
CYPRESS RUN: [9087](https://dashboard.cypress.io/projects/xr7gft/runs/9087/specs)
TEST START: 2023-11-27T14:40:52.407Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10051](http://condorpiedra.andes.gob.ar:85/10051/mochawesome.html)
CYPRESS RUN: [9160](https://dashboard.cypress.io/projects/xr7gft/runs/9160/specs)
TEST START: 2023-12-13T14:58:55.224Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10248](http://condorpiedra.andes.gob.ar:85/10248/mochawesome.html)
CYPRESS RUN: [9355](https://dashboard.cypress.io/projects/xr7gft/runs/9355/specs)
TEST START: 2024-01-12T13:02:55.556Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10256](http://condorpiedra.andes.gob.ar:85/10256/mochawesome.html)
CYPRESS RUN: [9363](https://dashboard.cypress.io/projects/xr7gft/runs/9363/specs)
TEST START: 2024-01-12T18:58:30.528Z
TOTAL: 365
SUCCESS: 348
FAIL: 14
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10271](http://condorpiedra.andes.gob.ar:85/10271/mochawesome.html)
CYPRESS RUN: [9378](https://dashboard.cypress.io/projects/xr7gft/runs/9378/specs)
TEST START: 2024-01-15T15:36:51.132Z
TOTAL: 401
SUCCESS: 398
FAIL: 0
SKIPPED: 3

**Review by MCele — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10342](http://condorpiedra.andes.gob.ar:85/10342/mochawesome.html)
CYPRESS RUN: [9449](https://dashboard.cypress.io/projects/xr7gft/runs/9449/specs)
TEST START: 2024-01-25T18:39:30.940Z
TOTAL: 401
SUCCESS: 398
FAIL: 0
SKIPPED: 3

**Review by negro89 — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10427](http://condorpiedra.andes.gob.ar:85/10427/mochawesome.html)
CYPRESS RUN: [9532](https://dashboard.cypress.io/projects/xr7gft/runs/9532/specs)
TEST START: 2024-02-02T11:41:51.028Z
TOTAL: 402
SUCCESS: 398
FAIL: 1
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10429](http://condorpiedra.andes.gob.ar:85/10429/mochawesome.html)
CYPRESS RUN: [9534](https://dashboard.cypress.io/projects/xr7gft/runs/9534/specs)
TEST START: 2024-02-02T12:42:29.154Z
TOTAL: 334
SUCCESS: 329
FAIL: 2
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10439](http://condorpiedra.andes.gob.ar:85/10439/mochawesome.html)
CYPRESS RUN: [9544](https://dashboard.cypress.io/projects/xr7gft/runs/9544/specs)
TEST START: 2024-02-05T13:49:03.240Z
TOTAL: 399
SUCCESS: 397
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10458](http://condorpiedra.andes.gob.ar:85/10458/mochawesome.html)
CYPRESS RUN: [9563](https://dashboard.cypress.io/projects/xr7gft/runs/9563/specs)
TEST START: 2024-02-07T12:46:38.597Z
TOTAL: 399
SUCCESS: 396
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10459](http://condorpiedra.andes.gob.ar:85/10459/mochawesome.html)
CYPRESS RUN: [9564](https://dashboard.cypress.io/projects/xr7gft/runs/9564/specs)
TEST START: 2024-02-07T13:04:32.683Z
TOTAL: 399
SUCCESS: 397
FAIL: 0
SKIPPED: 2

**Pull request merged**
