### PR TITLE
TOP - Listado reglas

### PR DESCRIPTION
**Pull request by palita1991**
### Requerimiento

https://proyectos.andes.gob.ar/browse/TOP-134

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7635](http://condorpiedra.andes.gob.ar:85/7635/mochawesome.html)
CYPRESS RUN: [6481](https://dashboard.cypress.io/projects/xr7gft/runs/6481/specs)
TEST START: 2022-09-14T17:36:20.464Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7637](http://condorpiedra.andes.gob.ar:85/7637/mochawesome.html)
CYPRESS RUN: [6538](https://dashboard.cypress.io/projects/xr7gft/runs/6538/specs)
TEST START: 2022-09-15T11:50:28.900Z
TOTAL: 406
SUCCESS: 388
FAIL: 17
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7653](http://condorpiedra.andes.gob.ar:85/7653/mochawesome.html)
CYPRESS RUN: [6583](https://dashboard.cypress.io/projects/xr7gft/runs/6583/specs)
TEST START: 2022-09-16T17:20:15.953Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7654](http://condorpiedra.andes.gob.ar:85/7654/mochawesome.html)
CYPRESS RUN: [6584](https://dashboard.cypress.io/projects/xr7gft/runs/6584/specs)
TEST START: 2022-09-16T18:00:25.277Z
TOTAL: 51
SUCCESS: 51
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Review by negro89 — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7783](http://condorpiedra.andes.gob.ar:85/7783/mochawesome.html)
CYPRESS RUN: [6921](https://dashboard.cypress.io/projects/xr7gft/runs/6921/specs)
TEST START: 2022-10-18T21:25:23.797Z
TOTAL: 323
SUCCESS: 315
FAIL: 7
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7785](http://condorpiedra.andes.gob.ar:85/7785/mochawesome.html)
CYPRESS RUN: [6923](https://dashboard.cypress.io/projects/xr7gft/runs/6923/specs)
TEST START: 2022-10-18T21:46:46.473Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7864](http://condorpiedra.andes.gob.ar:85/7864/mochawesome.html)
CYPRESS RUN: [6999](https://dashboard.cypress.io/projects/xr7gft/runs/6999/specs)
TEST START: 2022-11-01T16:53:01.867Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8102](http://condorpiedra.andes.gob.ar:85/8102/mochawesome.html)
CYPRESS RUN: [7292](https://dashboard.cypress.io/projects/xr7gft/runs/7292/specs)
TEST START: 2022-12-06T17:02:50.586Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8105](http://condorpiedra.andes.gob.ar:85/8105/mochawesome.html)
CYPRESS RUN: [7294](https://dashboard.cypress.io/projects/xr7gft/runs/7294/specs)
TEST START: 2022-12-06T18:03:22.735Z
TOTAL: 371
SUCCESS: 360
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8106](http://condorpiedra.andes.gob.ar:85/8106/mochawesome.html)
CYPRESS RUN: [7295](https://dashboard.cypress.io/projects/xr7gft/runs/7295/specs)
TEST START: 2022-12-06T18:14:27.995Z
TOTAL: 406
SUCCESS: 389
FAIL: 15
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8113](http://condorpiedra.andes.gob.ar:85/8113/mochawesome.html)
CYPRESS RUN: [7300](https://dashboard.cypress.io/projects/xr7gft/runs/7300/specs)
TEST START: 2022-12-07T12:58:14.896Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8114](http://condorpiedra.andes.gob.ar:85/8114/mochawesome.html)
CYPRESS RUN: [7301](https://dashboard.cypress.io/projects/xr7gft/runs/7301/specs)
TEST START: 2022-12-07T14:30:18.440Z
TOTAL: 406
SUCCESS: 389
FAIL: 15
SKIPPED: 2

**Review by MCele — APPROVED** [review]

**Pull request merged**
