### PR TITLE
CIT - Agregar filtro buscar a los parametros ingresados

### PR DESCRIPTION
**Pull request by Fabio-Ramirez**
### Requerimiento

https://proyectos.andes.gob.ar/browse/RUP-348

### Funcionalidad desarrollada 

1.  Se agrega nuevo atributo (search) a los parametros que ingresan como filtros

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9191](http://condorpiedra.andes.gob.ar:85/9191/mochawesome.html)
CYPRESS RUN: [8337](https://dashboard.cypress.io/projects/xr7gft/runs/8337/specs)
TEST START: 2023-07-11T12:54:28.277Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

**Review by MarianoCampetella — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9223](http://condorpiedra.andes.gob.ar:85/9223/mochawesome.html)
CYPRESS RUN: [8369](https://dashboard.cypress.io/projects/xr7gft/runs/8369/specs)
TEST START: 2023-07-17T19:05:44.357Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9225](http://condorpiedra.andes.gob.ar:85/9225/mochawesome.html)
CYPRESS RUN: [8371](https://dashboard.cypress.io/projects/xr7gft/runs/8371/specs)
TEST START: 2023-07-18T11:33:24.777Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9227](http://condorpiedra.andes.gob.ar:85/9227/mochawesome.html)
CYPRESS RUN: [8373](https://dashboard.cypress.io/projects/xr7gft/runs/8373/specs)
TEST START: 2023-07-18T12:24:41.318Z
TOTAL: 344
SUCCESS: 326
FAIL: 16
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9257](http://condorpiedra.andes.gob.ar:85/9257/mochawesome.html)
CYPRESS RUN: [8403](https://dashboard.cypress.io/projects/xr7gft/runs/8403/specs)
TEST START: 2023-07-24T18:51:07.343Z
TOTAL: 385
SUCCESS: 382
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9259](http://condorpiedra.andes.gob.ar:85/9259/mochawesome.html)
CYPRESS RUN: [8405](https://dashboard.cypress.io/projects/xr7gft/runs/8405/specs)
TEST START: 2023-07-25T12:23:25.799Z
TOTAL: 366
SUCCESS: 356
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9322](http://condorpiedra.andes.gob.ar:85/9322/mochawesome.html)
CYPRESS RUN: [8464](https://dashboard.cypress.io/projects/xr7gft/runs/8464/specs)
TEST START: 2023-08-01T18:02:40.837Z
TOTAL: 351
SUCCESS: 340
FAIL: 10
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [9333](http://condorpiedra.andes.gob.ar:85/9333/mochawesome.html)
CYPRESS RUN: [8473](https://dashboard.cypress.io/projects/xr7gft/runs/8473/specs)
TEST START: 2023-08-02T19:15:19.244Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Review by negro89 — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10352](http://condorpiedra.andes.gob.ar:85/10352/mochawesome.html)
CYPRESS RUN: [9459](https://dashboard.cypress.io/projects/xr7gft/runs/9459/specs)
TEST START: 2024-01-26T14:39:38.852Z
TOTAL: 401
SUCCESS: 399
FAIL: -1
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10440](http://condorpiedra.andes.gob.ar:85/10440/mochawesome.html)
CYPRESS RUN: [9545](https://dashboard.cypress.io/projects/xr7gft/runs/9545/specs)
TEST START: 2024-02-05T14:02:44.213Z
TOTAL: 402
SUCCESS: 400
FAIL: -1
SKIPPED: 3

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10484](http://condorpiedra.andes.gob.ar:85/10484/mochawesome.html)
CYPRESS RUN: [9585](https://dashboard.cypress.io/projects/xr7gft/runs/9585/specs)
TEST START: 2024-02-15T12:07:28.549Z
TOTAL: 399
SUCCESS: 396
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10485](http://condorpiedra.andes.gob.ar:85/10485/mochawesome.html)
CYPRESS RUN: [9586](https://dashboard.cypress.io/projects/xr7gft/runs/9586/specs)
TEST START: 2024-02-15T12:23:41.013Z
TOTAL: 399
SUCCESS: 395
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10486](http://condorpiedra.andes.gob.ar:85/10486/mochawesome.html)
CYPRESS RUN: [9587](https://dashboard.cypress.io/projects/xr7gft/runs/9587/specs)
TEST START: 2024-02-15T12:44:44.017Z
TOTAL: 399
SUCCESS: 397
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: framirez  
BUILD NUMBER: [10546](http://condorpiedra.andes.gob.ar:85/10546/mochawesome.html)
CYPRESS RUN: [9645](https://dashboard.cypress.io/projects/xr7gft/runs/9645/specs)
TEST START: 2024-02-26T11:45:20.787Z
TOTAL: 399
SUCCESS: 396
FAIL: 1
SKIPPED: 2

**Review by Fabio-Ramirez — COMMENTED** [review]
En el test existe un caso de mapa de camas (deshacer internación), donde es una cuestión que se desestima por el momento y no influye en esta tarea. Adjunto imagen del test en cuestión. 
image (5)

**Comment by negro89** [comment]
Tests al 08/05/24
image

**Pull request merged**
