### PR TITLE
feat(RUP): se agregan atributos a PlantillasRUPSchema

### PR DESCRIPTION
**Pull request by waltergarrido**
### Requerimiento

https://proyectos.andes.gob.ar/browse/RUP-231
### Funcionalidad desarrollada 

1. Se agregan dos atributos a PlantillasRUPSchema
2. 
3. 

### UserStories llegó a completarse

- [X] Si
- [] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: wgarrido  
BUILD NUMBER: [3767](http://condorpiedra.andes.gob.ar:85/3767/mochawesome.html)
CYPRESS RUN: [2832](https://dashboard.cypress.io/projects/xr7gft/runs/2832/specs)
TEST START: 2021-04-15T15:48:36.010Z
TOTAL: 366
SUCCESS: 365
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: wgarrido  
BUILD NUMBER: [3782](http://condorpiedra.andes.gob.ar:85/3782/mochawesome.html)
CYPRESS RUN: [2847](https://dashboard.cypress.io/projects/xr7gft/runs/2847/specs)
TEST START: 2021-04-16T11:34:59.521Z
TOTAL: 315
SUCCESS: 304
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Review by liquid36 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3791](http://condorpiedra.andes.gob.ar:85/3791/mochawesome.html)
CYPRESS RUN: [2856](https://dashboard.cypress.io/projects/xr7gft/runs/2856/specs)
TEST START: 2021-04-16T17:03:18.614Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

**Review by plammel — APPROVED** [review]

**Review by negro89 — APPROVED** [review]

**Review by martinebucarey — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3900](http://condorpiedra.andes.gob.ar:85/3900/mochawesome.html)
CYPRESS RUN: [2956](https://dashboard.cypress.io/projects/xr7gft/runs/2956/specs)
TEST START: 2021-04-30T16:22:29.288Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

**Pull request merged**
