### PR TITLE
CIT: queries en prestación de agenda

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento

https://proyectos.andes.gob.ar/browse/CIT-153
### Funcionalidad desarrollada 

1. array de ids de queries en `agenda.tipoPrestaciones`
2.  Crear Permiso para carga de pacientes masivos en una agenda
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5704](http://condorpiedra.andes.gob.ar:85/5704/mochawesome.html)
CYPRESS RUN: [4628](https://dashboard.cypress.io/projects/xr7gft/runs/4628/specs)
TEST START: 2021-12-22T12:31:01.332Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5709](http://condorpiedra.andes.gob.ar:85/5709/mochawesome.html)
CYPRESS RUN: [4633](https://dashboard.cypress.io/projects/xr7gft/runs/4633/specs)
TEST START: 2021-12-22T18:01:49.058Z
TOTAL: 404
SUCCESS: 384
FAIL: 19
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5745](http://condorpiedra.andes.gob.ar:85/5745/mochawesome.html)
CYPRESS RUN: [4669](https://dashboard.cypress.io/projects/xr7gft/runs/4669/specs)
TEST START: 2022-01-03T13:33:23.893Z
TOTAL: 382
SUCCESS: 367
FAIL: 14
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5776](http://condorpiedra.andes.gob.ar:85/5776/mochawesome.html)
CYPRESS RUN: [4699](https://dashboard.cypress.io/projects/xr7gft/runs/4699/specs)
TEST START: 2022-01-06T14:01:15.914Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5931](http://condorpiedra.andes.gob.ar:85/5931/mochawesome.html)
CYPRESS RUN: [4848](https://dashboard.cypress.io/projects/xr7gft/runs/4848/specs)
TEST START: 2022-02-15T17:11:09.922Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5932](http://condorpiedra.andes.gob.ar:85/5932/mochawesome.html)
CYPRESS RUN: [4849](https://dashboard.cypress.io/projects/xr7gft/runs/4849/specs)
TEST START: 2022-02-15T17:20:46.572Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5940](http://condorpiedra.andes.gob.ar:85/5940/mochawesome.html)
CYPRESS RUN: [4857](https://dashboard.cypress.io/projects/xr7gft/runs/4857/specs)
TEST START: 2022-02-17T15:53:29.556Z
TOTAL: 343
SUCCESS: 331
FAIL: 11
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5941](http://condorpiedra.andes.gob.ar:85/5941/mochawesome.html)
CYPRESS RUN: [4858](https://dashboard.cypress.io/projects/xr7gft/runs/4858/specs)
TEST START: 2022-02-17T16:03:17.174Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

**Review by martinebucarey — APPROVED** [review]

**Pull request merged**
