### PR TITLE
TM - Configuracion de internacion por conceptos turnuables

### PR DESCRIPTION
**Pull request by negro89**
### Requerimiento
https://proyectos.andes.gob.ar/browse/TM-25

### Funcionalidad desarrollada 

1. Nuevo atributo 'checkRupTiposPrestacion' en esquema de estados

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si (Ver pr en app https://github.com/andes/app/pull/2772)
- [ ] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7861](http://condorpiedra.andes.gob.ar:85/7861/mochawesome.html)
CYPRESS RUN: [6996](https://dashboard.cypress.io/projects/xr7gft/runs/6996/specs)
TEST START: 2022-11-01T15:56:36.727Z
TOTAL: 406
SUCCESS: 394
FAIL: 11
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7865](http://condorpiedra.andes.gob.ar:85/7865/mochawesome.html)
CYPRESS RUN: [7000](https://dashboard.cypress.io/projects/xr7gft/runs/7000/specs)
TEST START: 2022-11-01T16:55:38.099Z
TOTAL: 406
SUCCESS: 389
FAIL: 16
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7903](http://condorpiedra.andes.gob.ar:85/7903/mochawesome.html)
CYPRESS RUN: [7098](https://dashboard.cypress.io/projects/xr7gft/runs/7098/specs)
TEST START: 2022-11-11T19:43:19.018Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7955](http://condorpiedra.andes.gob.ar:85/7955/mochawesome.html)
CYPRESS RUN: [7148](https://dashboard.cypress.io/projects/xr7gft/runs/7148/specs)
TEST START: 2022-11-17T12:48:29.097Z
TOTAL: 406
SUCCESS: 398
FAIL: 7
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7958](http://condorpiedra.andes.gob.ar:85/7958/mochawesome.html)
CYPRESS RUN: [7151](https://dashboard.cypress.io/projects/xr7gft/runs/7151/specs)
TEST START: 2022-11-17T13:29:27.197Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

**Review by MarianoCampetella — APPROVED** [review]

**Review by silviroa — APPROVED** [review]

**Pull request merged**
