### PR TITLE
AM: permitir registro de familiar con scan del dni

### PR DESCRIPTION
**Pull request by juuliotero**
### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-209

### Funcionalidad desarrollada 
1. Obtener los datos del familiar a asociar del scan en /registro-familiar

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Review by plammel — APPROVED** [review]

**Review by liquid36 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5553](http://condorpiedra.andes.gob.ar:85/5553/mochawesome.html)
CYPRESS RUN: [4488](https://dashboard.cypress.io/projects/xr7gft/runs/4488/specs)
TEST START: 2021-11-30T18:18:40.043Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5554](http://condorpiedra.andes.gob.ar:85/5554/mochawesome.html)
CYPRESS RUN: [4489](https://dashboard.cypress.io/projects/xr7gft/runs/4489/specs)
TEST START: 2021-11-30T18:30:05.868Z
TOTAL: 344
SUCCESS: 340
FAIL: 3
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5556](http://condorpiedra.andes.gob.ar:85/5556/mochawesome.html)
CYPRESS RUN: [4491](https://dashboard.cypress.io/projects/xr7gft/runs/4491/specs)
TEST START: 2021-12-01T12:01:43.326Z
TOTAL: 402
SUCCESS: 393
FAIL: 8
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: jotero  
BUILD NUMBER: [5575](http://condorpiedra.andes.gob.ar:85/5575/mochawesome.html)
CYPRESS RUN: [4510](https://dashboard.cypress.io/projects/xr7gft/runs/4510/specs)
TEST START: 2021-12-03T17:58:49.386Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

**Pull request merged**
